version: '2'
services:
    activityserver-mongodb:
        container_name: activityserver-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb activityserver-mongodb-config
    activityserver-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    activityserver-mongodb-config:
        image: mongo:3.2.10
        container_name: activityserver-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
